import { LitElement } from 'lit';
type MenuItem = {
    label: string;
    icon?: string;
    selected?: boolean;
    disabled?: boolean;
    external?: boolean;
    notifications?: number;
    nestedMenu?: MenuItem[];
};
export declare class Sidemenu extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentClickBound;
    private _handleResizeBound;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    topMenuItems: MenuItem[];
    createMenuItems: MenuItem[];
    roleMenuItems: MenuItem[];
    globalMenuItems: MenuItem[];
    axiaHidden: boolean;
    axiaDisabled: boolean;
    axiaLabel: string;
    expanded: boolean;
    disabled: boolean;
    toggleLabel: string;
    createLabel: string;
    createMenuPosition: string;
    createNotifications: number;
    createDisabled: boolean;
    hideCreateMenu: boolean;
    _hasManualSelected: boolean;
    _toggleDisabled: boolean;
    _showCreateDropdown: boolean;
    private get _createNotification();
    private get _createSection();
    private _propagateProperties;
    private _resizeTimer;
    private _handleResize;
    _getHiddenRoleNotifications(): void;
    _othersTopItem: HTMLElement | null;
    private _getTopMenuItems;
    private _updateTopMenu;
    private _checkWindowInnerwidth;
    private _clickedOutsideCreateMenu;
    _closeCreateDropdown(): void;
    _handleKeydownEscape(event: CustomEvent): void;
    _handleDocumentClick(event: Event): void;
    _openCreateMenu(): void;
    _toggleCreateMenuTooltip(): void;
    _toggleSidemenu(): void;
    _handleCreateMouseEnter(): void;
    _handleCreateMouseLeave(): void;
    _handleCreateMouseDown(): void;
    _handleCreateFocusout(event: any): void;
    _handleCreateMouseUp(): void;
    _handleMenuClick(event: MouseEvent, item: MenuItem): void;
    _selectSidenenuItem(event: MouseEvent): void;
    private _dropdown;
    private _getCreateDropdownFixedPosition;
    _handleContainerScroll(): void;
    _handleAxia(): void;
    private _isFirstUpdated;
    firstUpdated(): Promise<void>;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    render(): import('lit-html').TemplateResult;
}
export {};
