import { LitElement } from 'lit';

export type CalendarItem = {
    date: string;
    type: string;
};
export type DssTimepickerOption = {
    value: string;
    state: string;
};
export declare class FormDatepicker extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    disconnectedCallback(): void;
    _addCalendarListener(): void;
    _removeCalendarListener(): void;
    _handleClickOut(event: any): void;
    _handleFocusOut(event: FocusEvent): void;
    _input: HTMLInputElement;
    _label: HTMLLabelElement;
    label: string;
    hideLabel: boolean;
    name: string;
    id: string;
    type: string;
    placeholder: string;
    value: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    step?: number;
    min?: number;
    max?: number;
    minLength?: number;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    size: string;
    icon: string;
    helpText?: string;
    showCalendar: boolean;
    dropdownPlacement: string;
    dropdownFixed: boolean;
    showTime: boolean;
    showButtons: boolean;
    leftLabel: string;
    rightLabel: string;
    minDate: string;
    maxDate: string;
    timepicker: string;
    timepickerLabel: string;
    minHour: number;
    maxHour: number;
    minutesRange: number;
    customCalendar: CalendarItem[] | undefined;
    customTimeListOptions: DssTimepickerOption[];
    validate: boolean;
    errorMessageFormat: string;
    errorMessageMinDate: string;
    errorMessageMaxDate: string;
    private _defaultId;
    _getEffectiveId(): string;
    _isFocused: boolean;
    _isTruncated: boolean;
    _externalPlaceholder: string;
    _previousDate: string;
    _inputValidity: boolean;
    _popperInstance: any;
    _placeholder: string;
    _helpText: string;
    _helpTextBackup: string;
    _oldHelpText: string;
    _isFirstUpdated: boolean;
    firstUpdated(): Promise<void>;
    updated(changedProps: Map<string, unknown>): void;
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    render(): import('lit-html').TemplateResult;
    _handleInput(event: any): void;
    _handleFocusin(): void;
    _focusInput(): void;
    _handleKeydown(e: KeyboardEvent): void;
    _emitInput(): void;
    _emitChange(): void;
    _checkInputOverflow(): void;
    _handleValidity(): void;
    _validateDate(): void;
    _checkDateFormat(date: string): boolean;
    _convertToISO(dateStr: string): string;
    _dispatchOnValidate(invalid: boolean): void;
    _formatDate(value: string): string;
    _onDateChange(e: CustomEvent): void;
    _onCancel(): void;
    _dispatchValueChange(): void;
    _clearDate(): void;
    _createPopperCalendar(): void;
    _closeCalendar(): void;
    _checkClickOutside(event: Event): void;
    _checkFocusOut(event: FocusEvent): void;
}
