import { LitElement } from 'lit';

export interface IFilter {
    value: string;
    icon: string;
}
export interface ITableColumnHeader {
    title: string;
    sort?: boolean;
}
export declare class Table extends LitElement {
    static get styles(): import('lit').CSSResult[];
    set hasPaginator(value: boolean);
    get hasPaginator(): boolean;
    set data(data: Array<any>);
    get data(): Array<any>;
    set customData(data: Array<any>);
    get customData(): Array<any>;
    set customTableHeader(value: Array<ITableColumnHeader>);
    get customTableHeader(): Array<ITableColumnHeader>;
    set filters(filters: Array<any>);
    get filters(): Array<any>;
    set currentIndex(value: number);
    get currentIndex(): number;
    set pageSize(value: number);
    get pageSize(): number;
    set pageSizeOptions(pageSizeOptions: string);
    get pageSizeOptions(): string;
    set resultstext(value: string);
    get resultstext(): string;
    set rowsperpagetext(value: string);
    get rowsperpagetext(): string;
    set textAlign(value: string);
    get textAlign(): string;
    set headerTitle(value: string);
    get headerTitle(): string;
    set hideHeader(value: boolean);
    get hideHeader(): boolean;
    set hideColumnHeader(value: boolean);
    get hideColumnHeader(): boolean;
    set innerFilters(value: boolean);
    get innerFilters(): boolean;
    set expandTable(value: boolean);
    get expandTable(): boolean;
    set expandLabel(value: string);
    get expandLabel(): string;
    set collapseLabel(value: string);
    get collapseLabel(): string;
    set rowsOnCollapsed(value: number);
    get rowsOnCollapsed(): number;
    set filtersLabel(value: string);
    get filtersLabel(): string;
    set cleanFiltersLabel(value: string);
    get cleanFiltersLabel(): string;
    set selectedRowsLabel(value: string);
    get selectedRowsLabel(): string;
    set footerButtons(value: number);
    get footerButtons(): number;
    set maxContentWidth(value: boolean);
    get maxContentWidth(): boolean;
    set stickyColumns(value: boolean);
    get stickyColumns(): boolean;
    set multiselect(value: boolean);
    get multiselect(): boolean;
    set radioselect(value: boolean);
    get radioselect(): boolean;
    set hasRowButton(value: boolean);
    get hasRowButton(): boolean;
    set rowButtonLabel(value: string);
    get rowButtonLabel(): string;
    set hasRowActions(value: boolean);
    get hasRowActions(): boolean;
    set rowActionsIcons(icons: Array<string>);
    get rowActionsIcons(): Array<string>;
    set footerButtonPrimaryLabel(value: string);
    get footerButtonPrimaryLabel(): string;
    set footerButtonSecondaryLabel(value: string);
    get footerButtonSecondaryLabel(): string;
    set footerButtonAlternativeLabel(value: string);
    get footerButtonAlternativeLabel(): string;
    set enableRowActionsOnDisabled(value: boolean);
    get enableRowActionsOnDisabled(): boolean;
    set enableRowActionsOnDeleted(value: boolean);
    get enableRowActionsOnDeleted(): boolean;
    set valueMaxLength(value: number);
    get valueMaxLength(): number;
    private get _tableGridStyle();
    private get _tableHeight();
    private _valueMaxLength;
    private _data;
    private _customData;
    private _pipeData;
    private _customTableHeader;
    private _filters;
    private _tableHeader;
    private _tableHeaderSort;
    private _hasPaginator;
    private _currentIndex;
    private _pageSize;
    private _pageSizeOptions;
    private _resultstext;
    private _rowsperpagetext;
    private _textAlign;
    private _headerTitle;
    private _hideHeader;
    private _hideColumnHeader;
    private _innerFilters;
    private _expandTable;
    private _expandLabel;
    private _collapseLabel;
    private _rowsOnCollapsed;
    private _filtersLabel;
    private _cleanFiltersLabel;
    private _openFiltersLabel;
    private _selectedRowsLabel;
    private _selectAllRows;
    private _noFiltersLabel;
    private _footerButtons;
    private _maxContentWidth;
    private _stickyColumns;
    private _multiselect;
    private _radioselect;
    private _hasRowButton;
    private _rowButtonLabel;
    private _hasRowActions;
    private _rowActionsIcons;
    private _footerButtonPrimaryLabel;
    private _footerButtonSecondaryLabel;
    private _footerButtonAlternativeLabel;
    private _enableRowActionsOnDeleted;
    private _enableRowActionsOnDisabled;
    private _currentSortColumn;
    private _currentSortType;
    private _copyPipeData;
    private _isFirstUpdate;
    firstUpdated(): Promise<void>;
    willUpdate(changedProperties: any): void;
    private _clickOutside;
    private _createTableHeader;
    private _sortBy;
    private _paginateTable;
    private _generateTableHeaderHTML;
    private _onRowCheckboxChange;
    private _onSelectAllRows;
    private _onRowAction;
    private _onRowActionKeydown;
    private _generateTableTdCheckbox;
    private _generateTableTdRadio;
    private _generateTableTdButton;
    private _generateTableTdActions;
    private _generateTableTdSelfActions;
    private _resetRowsTabIndex;
    private _uncheckRadioRows;
    private _generateDefaultTableBody;
    private _generateCustomTableBody;
    private _generateFilterChips;
    private _clearFilters;
    private _countRowsChecked;
    private _getRowsSelected;
    private _emitExpandAction;
    private _emitOpenFilters;
    private _emitChangeFilters;
    private _emitFooterAction;
    render(): import('lit-html').TemplateResult<1>;
}
