import { LitElement } from 'lit';
import { TimepickerOptionItem } from '../timepicker/timepicker';
export declare class TimepickerOptions extends LitElement {
    private _manualValueSyncQueued;
    static get styles(): import('lit').CSSResult[];
    disconnectedCallback(): void;
    open: boolean;
    value: string | null;
    variant: string;
    timeListOptions: string[];
    customTimeListOptions: TimepickerOptionItem[];
    timeManualHourOptions: string[];
    timeManualMinutesOptions: string[];
    manualHourSelector: string;
    manualMinuteSelector: string;
    _isFirstUpdated: boolean;
    _floatingCombobox: HTMLElement;
    delay: number;
    private _parent?;
    private _initialParent;
    private _cleanupAutoUpdate?;
    private _showTimeout?;
    private _hideTimeout?;
    private _portalManager;
    firstUpdated(): Promise<void>;
    updated(changedProps: Map<string, unknown>): void;
    _toggle: () => void;
    show(): void;
    private _executeShow;
    hide(): void;
    updateFloatingCombobox(): void;
    private _updatePosition;
    _generateTimeListOptionsHTML(options: string[], customOptions?: TimepickerOptionItem[]): import('lit-html').TemplateResult[];
    _generateTimeManualOptionsHTML(inputName: string, options: string[]): import('lit-html').TemplateResult[];
    _handleManualCancel(): void;
    _handleManualAccept(): void;
    _checkDisableTimeManualSelector(): boolean;
    _timeListOptionsScrollTo(value?: string): void;
    _timeManualOptionsScrollTo(): void;
    _updateManualValues(): void;
    _scheduleManualValueSync(): void;
    _parsePartialTime(value?: string | null): {
        hour?: string | undefined;
        minute?: string | undefined;
    };
    _hourManualScrollTo(value?: string): void;
    _minutesManualScrollTo(value?: string): void;
    _emitValueChange(value: string): void;
    _emitCancel(): void;
    _focusFirstElement(): void;
    _focusListItem(): void;
    _focusManualHourItem(): void;
    _focusSentinel(): void;
    render(): import('lit-html').TemplateResult;
}
