import { LitElement } from 'lit';
export declare class Accordion extends LitElement {
    static get styles(): import('lit').CSSResult[];
    showHeaderDivider: boolean;
    hideFooterDivider: boolean;
    hideTooltip: boolean;
    info: string | undefined;
    infoBadgeStatus: string;
    set infoBadgeState(value: string);
    get infoBadgeState(): string;
    infoBadgeIcon: string;
    infoBadgeOutlined: boolean;
    secondaryActionLabel: string;
    secondaryActionFill: boolean;
    hasPrimaryAction: boolean;
    primaryActionLabel: string;
    primaryActionIcon: string;
    primaryActionStatus: string;
    primaryActionDisabled: boolean;
    primaryActionFill: boolean;
    helpText: string | null;
    get _checkbox(): HTMLInputElement;
    icon: string;
    iconStatus: string;
    titleText: string;
    type: string;
    index: number | undefined;
    isOpen: boolean;
    accordionStyle: 'box' | 'inner';
    results: number | undefined;
    resultsLabel: string;
    set resultsText(value: string);
    get resultsText(): string;
    resultsStatus: string;
    hasCheckbox: boolean;
    hasSecondaryAction: boolean;
    secondaryActionIcon: string;
    secondaryActionStatus: string;
    secondaryActionDisabled: boolean;
    set resultsState(value: string);
    get resultsState(): string;
    notifications: number | undefined;
    notificationsStatus: string;
    set notificationsState(value: string);
    get notificationsState(): string;
    widget: boolean;
    widgetBadgeStatus: string;
    set widgetBadgeState(value: string);
    get widgetBadgeState(): string;
    widgetBadgeLabel: string | undefined;
    set widgetBadgeText(value: string);
    get widgetBadgeText(): string;
    widgetShowNext: boolean;
    widgetShowClose: boolean;
    _toggleAccordion(): void;
    _dispatchCheckboxChange(): void;
    _dispatchSecondaryAction(): void;
    _dispatchPrimaryAction(): void;
    _dispatchToggleAccordion(): void;
    _dispatchWidgetNext(): void;
    _dispatchWidgetClose(): void;
    render(): import('lit-html').TemplateResult;
}
