import { LitElement } from 'lit';

export type CalendarItem = {
    date: string;
    type: string;
};
export type DssTimepickerOption = {
    value: string;
    state: string;
};
export declare class FormDatepickerRange extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    disconnectedCallback(): void;
    _addCalendarListener(): void;
    _removeCalendarListener(): void;
    _handleClickOut(event: any): void;
    _handleFocusOut(event: FocusEvent): void;
    _inputRangeStart: HTMLInputElement;
    _inputRangeEnd: HTMLInputElement;
    _hiddenInput: HTMLInputElement;
    labelRangeStart: string;
    labelRangeEnd: string;
    hideLabel: boolean;
    name: string;
    id: string;
    type: string;
    placeholderRangeStart: string;
    placeholderRangeEnd: string;
    value: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    step?: number;
    min?: number;
    max?: number;
    minLength?: number;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    size: string;
    iconRangeStart: string;
    iconRangeEnd: string;
    helpText?: string;
    showCalendar: boolean;
    dropdownPlacement: string;
    dropdownFixed: boolean;
    showButtons: boolean;
    minDate: string;
    maxDate: string;
    timepicker: string;
    timepickerLabel: string;
    minHour: number;
    maxHour: number;
    minutesRange: number;
    customCalendar: CalendarItem[] | undefined;
    customTimeListOptions: DssTimepickerOption[];
    validate: boolean;
    errorMessageFormat: string;
    errorMessageMinDate: string;
    errorMessageMaxDate: string;
    calendarLeftButtonLabel: string;
    calendarRightButtonLabel: string;
    private _defaultStartId;
    private _defaultEndId;
    _getEffectiveStartId(): string;
    _getEffectiveEndId(): string;
    _isStartFocused: boolean;
    _isEndFocused: boolean;
    _isTruncated: boolean;
    _helpText: string;
    _dateformatPlaceholder: string;
    _copyInputRangeStartPlaceholder: string;
    _copyInputRangeEndPlaceholder: string;
    _popperInstance: any;
    _placeholderStart: string;
    _placeholderEnd: string;
    _helpTextBackup: string;
    _isFirstUpdated: boolean;
    firstUpdated(): Promise<void>;
    updated(changedProps: Map<string, unknown>): void;
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    render(): import('lit-html').TemplateResult;
    _applyValue(): void;
    _handleRangeStartInput(event: Event): void;
    _handleRangeEndInput(event: Event): void;
    _handleRangeStartClick(): void;
    _handleRangeEndClick(): void;
    _handleRangeStartFocusIn(): void;
    _handleRangeEndFocusIn(): void;
    _handleRangeKeydown(e: KeyboardEvent): void;
    _dispatchValueChange(rangeValues: any): void;
    _updateHiddenInput(): void;
    _emitChange(): void;
    _onCalendarChange(event: CustomEvent): void;
    _onCalendarCancel(): void;
    _updatePlaceholders(): void;
    _removePlaceholders(): void;
    _validateDate(): void;
    _checkDateFormat(date: string): boolean;
    _convertToISO(dateStr: string): string;
    _dispatchOnValidate(invalid: boolean): void;
    _formatDate(value: string): string;
    _clearDate(range: 'rangeStart' | 'rangeEnd'): void;
    _createPopperCalendar(): void;
    _closeCalendar(): void;
    _checkClickOutside(event: Event): void;
    _checkFocusOut(event: FocusEvent): void;
}
