import { LitElement } from 'lit';

export type DssTimepickerOption = {
    value: string;
    state: string;
};
export declare class DatepickerRange extends LitElement {
    static get styles(): import('lit').CSSResult[];
    get _inputRangeStart(): HTMLInputElement;
    get _inputRangeEnd(): HTMLInputElement;
    set iconRangeStart(value: string);
    set iconRangeEnd(value: string);
    set minDate(minDate: string);
    set maxDate(maxDate: string);
    set invalid(invalid: boolean);
    set inputSize(size: string);
    set helpText(text: string);
    set showButtons(showButtons: boolean);
    set calendarLeftButtonLabel(leftLabel: string);
    set calendarRightButtonLabel(rightLabel: string);
    _iconRangeStart: string;
    _iconRangeEnd: string;
    _dateformatPlaceholder: string;
    _isStartFocused: boolean;
    _isEndFocused: boolean;
    _invalid: boolean;
    _showCalendar: boolean;
    _helpText: string;
    _minDate: string;
    _maxDate: string;
    _inputSize: string;
    _calendarShowButtons: boolean;
    _calendarLeftButtonLabel: string;
    _calendarRightButtonLabel: string;
    _copyInputRangeStartPlaceholder: string;
    _copyInputRangeEndPlaceholder: string;
    _isFirstInputsCheck: boolean;
    _checkInputAttributes(): void;
    _updatePlaceholders(): void;
    _removePlaceholders(): void;
    _handleRangeStartInput(event: Event): void;
    _handleRangeEndInput(event: Event): void;
    _handleRangeStartClick(): void;
    _handleRangeEndClick(): void;
    _handleRangeStartFocusIn(): void;
    _handleRangeEndFocusIn(): void;
    _handleRangeKeydown(e: KeyboardEvent): void;
    _onCalendarChange(event: CustomEvent): void;
    _onCalendarCancel(): void;
    _closeCalendar(): void;
    _formatDate(value: string): string;
    observerConfig: {
        attributes: boolean;
        childList: boolean;
        subtree: boolean;
    };
    callback: (mutationList: any) => void;
    observer: MutationObserver;
    disconnectedCallback(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
