import { LitElement } from 'lit';

export declare class ActionMenuItem extends LitElement {
    static get styles(): import('lit').CSSResult[];
    set state(value: string);
    get state(): string;
    set label(value: string);
    get label(): string;
    set leftIcon(value: string);
    get leftIcon(): string;
    set rightIcon(value: string);
    get rightIcon(): string;
    set actionIcon(value: string);
    get actionIcon(): string;
    set actionState(value: string);
    get actionState(): string;
    set notifications(value: number);
    get notifications(): number;
    set notificationsState(value: string);
    get notificationsState(): string;
    set selected(value: boolean);
    get selected(): boolean;
    set disabled(value: boolean);
    get disabled(): boolean;
    set hasNestedMenu(value: boolean);
    get hasNestedMenu(): boolean;
    set nestedMenuPosition(value: string);
    get nestedMenuPosition(): string;
    set first(value: boolean);
    get first(): boolean;
    set last(value: boolean);
    get last(): boolean;
    _state: string;
    _label: string;
    _leftIcon: string | undefined;
    _rightIcon: string | undefined;
    _actionIcon: string | undefined;
    _actionState: string;
    _notifications: number;
    _notificationsState: string;
    _selected: boolean;
    _disabled: boolean;
    _hasNestedMenu: boolean;
    _nestedMenuPosition: string;
    _first: boolean;
    _last: boolean;
    _handleItemClick(): void;
    _handleKeydown(event: KeyboardEvent): void;
    _handleAction(event: Event): void;
    private _clickOutside;
    private _unselectItem;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
