import { LitElement } from 'lit';
export type CatalogOption = {
    value: string;
    icon?: string;
    disabled?: boolean;
    key?: string;
    data?: any;
};
export declare class SearchBar extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    _input: HTMLInputElement;
    _combobox: HTMLInputElement;
    value: string;
    multiple: boolean;
    icon: string;
    size: string;
    helpText: string | undefined;
    innerFocus: boolean;
    threshold: number;
    maxTermChips: number;
    searchTerms: string[];
    searchItems: any[];
    emptyDropdownText: string;
    catalogLabel: string;
    catalog: CatalogOption[];
    recentSearchesLabel: string;
    recentSearches: CatalogOption[];
    isCatalogLoading: boolean;
    catalogStyle: string;
    advancedFilter: boolean;
    placeholder: string;
    _filter: string;
    _isFocused: boolean;
    _showClearButton: boolean;
    _filteredCatalog: CatalogOption[];
    _filteredRecentSearches: CatalogOption[];
    _showAllChips: boolean;
    _showDropdown: boolean;
    serverSideFilter: boolean;
    id: string;
    name: string;
    label: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    private _defaultId;
    tooltipFixed: boolean;
    forceViewport: boolean;
    _isTruncated: boolean;
    _isCatalogLoaded: boolean;
    private _handleDocumentMouseDown;
    private _portalManager;
    private visibleObserver;
    _getPortalCombobox(): Element | null | undefined;
    updated(changedProps: Map<string, unknown>): void;
    disconnectedCallback(): void;
    _getEffectiveId(): string;
    get _inputValidity(): boolean;
    _handleInput(): void;
    _handleClickOutside(event: any): void;
    _handleFocusIn(): void;
    _handleFocusOut(event: any): void;
    _handleCatalogFocusOut(): void;
    _handleKeyDown(e?: KeyboardEvent): void;
    _focusInput(): void;
    _handleValidity(): void;
    _clearSearch(): void;
    _hideDropdown(): void;
    _getFilterCatalog(filter: string): CatalogOption[];
    _applyDefaultCatalogFilter(filter: string): CatalogOption[];
    _applyAdvancedCatalogFilter(filter: string): CatalogOption[];
    _getFilterSearches(filter: string): CatalogOption[];
    _applyDefaultSearchesFilter(filter: string): CatalogOption[];
    _applyAdvancedSearchesFilter(filter: string): CatalogOption[];
    _handleMultipleTermDelete(term: string): void;
    _dispatchSearchChange(item?: CatalogOption): void;
    _emitInput(): void;
    _handleChange(): void;
    _emitChange(): void;
    _closeDropdown(): void;
    _addDropdownListeners(): void;
    _removeDropdownListeners(): void;
    firstUpdated(): Promise<void>;
    _lastValue: string | null;
    _handleMouseOver(): void;
    _handleCatalogItemSelected(e: CustomEvent): void;
    _checkInputOverflow(): void;
    render(): import('lit-html').TemplateResult;
}
