import { LitElement } from 'lit';
export type CatalogOption = {
    value: string;
    icon?: string;
};
export declare class SearchBar extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    _input: HTMLInputElement;
    value: string;
    multiple: boolean;
    icon: string;
    size: string;
    helpText: string | undefined;
    innerFocus: boolean;
    threshold: number;
    searchTerms: string[];
    catalog: CatalogOption[];
    emptyDropdownText: string;
    recentSearchesLabel: string;
    recentSearches: boolean;
    isCatalogLoading: boolean;
    dropdownStyle: string;
    catalogStyle: string;
    advancedFilter: boolean;
    placeholder: string;
    _filter: string;
    _isFocused: boolean;
    _showClearButton: boolean;
    _filteredCatalog: CatalogOption[];
    _showAllChips: boolean;
    _showDropdown: boolean;
    _dropdownStyle: string;
    id: string;
    name: string;
    label: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    private _defaultId;
    updated(changedProps: Map<string, unknown>): void;
    _getEffectiveId(): string;
    _getSearchStyle(): string;
    get _inputValidity(): boolean;
    _handleInput(): void;
    _handleFocusIn(): void;
    _handleFocusOut(): void;
    _handleKeyDown(e?: KeyboardEvent): void;
    _focusInput(): void;
    _handleValidity(): void;
    _clearSearch(): void;
    _hideDropdown(): void;
    _getFilterCatalog(filter: string): CatalogOption[];
    _applyDefaultFilter(filter: string): CatalogOption[];
    _applyAdvancedFilter(filter: string): CatalogOption[];
    _generateSearchChips(): import('lit-html').TemplateResult[];
    _generateFilterCatalog(): import('lit-html').TemplateResult[];
    _dispatchSearchChange(): void;
    _emitInput(): void;
    _handleChange(): void;
    _emitChange(): void;
    _closeDropdown(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
