import { LitElement } from 'lit';
export type FormSelectOption = {
    label: string;
    value: string;
};
export declare class SelectOptions extends LitElement {
    static get styles(): import('lit').CSSResult[];
    disconnectedCallback(): void;
    isOpen: boolean;
    openByDefault: boolean;
    elements: Array<FormSelectOption> | null;
    value: Array<FormSelectOption> | Array<string> | null;
    _value: Array<FormSelectOption> | null;
    type: 'default' | 'green';
    filter: string | null;
    multiple: boolean;
    tick: boolean;
    deselectable: boolean;
    selectAll: boolean;
    readonly: boolean;
    disabled: boolean;
    boxShadow: boolean;
    advancedFilter: boolean;
    searchThreshold: number;
    filterThreshold: number;
    boxStyle: string;
    selectedCounter: number;
    ariaLabel: string | null;
    labelSelectAll: string;
    labelDeselectAll: string;
    emptySelectorLabel: string;
    emptyFilterLabel: string;
    _elementId: string;
    _elementSelectAll: string[];
    _style: string | null;
    _isAllSelected: boolean;
    _isFirstUpdated: boolean;
    _floatingCombobox: HTMLElement;
    delay: number;
    private _parent?;
    private _initialParent;
    private _cleanupAutoUpdate?;
    private _showTimeout?;
    private _hideTimeout?;
    private _portalManager;
    private _isTabbingOut;
    _toggle: () => void;
    show(): void;
    private _executeShow;
    hide(): void;
    updateFloatingCombobox(): void;
    private _updatePosition;
    _syncSelectedValue: boolean;
    updated(changedProps: Map<string, any>): void;
    firstUpdated(): Promise<void>;
    _checkElements(): void;
    _updateSelectedValues(): void;
    _areAllElementsSelected(): void;
    _valueIsSelected(value: string): boolean;
    _manuallySelect(e: Event, value: string): void;
    _manuallySelectAll(e: Event): void;
    _returnSelecteAllValues(selectAll: boolean): void;
    _returnSelectedValues(value: string): void;
    selectFirstMatch(): void;
    moveFocus(): void;
    _focusEvent(e: Event): void;
    _blurEvent(e: Event): void;
    _handleKeyDown(e: KeyboardEvent): void;
    _handleFocusOut(e: FocusEvent): void;
    _focusSentinel(): void;
    render(): import('lit-html').TemplateResult;
}
