import { LitElement } from 'lit';
export declare class Slider extends LitElement {
    static get styles(): import('lit').CSSResult;
    private _handleDomContentLoaded;
    private _handleInputEvent;
    private _handleMouseUp;
    private _handleKeyUp;
    private _handleTouchStartEvent;
    private _handleTouchMoveEvent;
    private _handleTouchEndEvent;
    get _input(): HTMLInputElement;
    get _tooltip(): HTMLElement;
    label: string;
    value: number;
    min: number;
    max: number;
    step: number;
    orientation: string;
    disabled: boolean;
    _progress: number;
    _vertical: boolean;
    _isTooltipTouched: boolean;
    set orient(orient: string);
    get orient(): string;
    updated(changedProperties: any): void;
    constructor();
    firstUpdated(): Promise<void>;
    disconnectedCallback(): void;
    _handleTouchStart(event: any): void;
    _handleTouchEnd(event: any): void;
    _handleTouchMove(event: any): void;
    _handleInput(): void;
    _setProgress(): void;
    _updateTooltip(): void;
    _dispatchValue(): void;
    render(): import('lit-html').TemplateResult;
}
