import { LitElement } from 'lit';

export declare class Slider extends LitElement {
    static get styles(): import('lit').CSSResult;
    private _handleDomContentLoaded;
    private _handleInputEvent;
    private _handleMouseUp;
    private _handleKeyUp;
    private _handleTouchStartEvent;
    private _handleTouchMoveEvent;
    private _handleTouchEndEvent;
    get _input(): HTMLInputElement;
    get _tooltip(): HTMLElement;
    set min(min: number);
    get min(): number;
    set max(max: number);
    get max(): number;
    set step(step: number);
    get step(): number;
    set orient(orient: string);
    get orient(): string;
    set value(value: number);
    get value(): number;
    set disabled(disabled: boolean);
    get disabled(): boolean;
    set label(label: string);
    get label(): string;
    _label: string;
    _min: number;
    _max: number;
    _step: number;
    _orient: string;
    _vertical: boolean;
    _value: number;
    _progress: number;
    _disabled: boolean;
    _isTooltipTouched: boolean;
    constructor();
    firstUpdated(): Promise<void>;
    disconnectedCallback(): void;
    _handleTouchStart(event: any): void;
    _handleTouchEnd(event: any): void;
    _handleTouchMove(event: any): void;
    _handleInput(): void;
    _setProgress(): void;
    _updateTooltip(): void;
    _dispatchValue(): void;
    render(): import('lit-html').TemplateResult;
}
