import { LitElement } from 'lit';
export declare class HeaderMenuProfessional extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentClickBound;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    disabled: boolean;
    name: string | undefined;
    center: string | undefined;
    collegiate: string | undefined;
    infoLabel: string;
    collegiateLabel: string;
    preferencesLabel: string;
    detailsLabel: string;
    detailsHref: string;
    detailsTarget: string;
    detailsIcon: string;
    detailsIconPosition: string;
    primaryActionLabel: string;
    primaryActionVariant: string;
    primaryActionStatus: string;
    primaryActionDisabled: boolean;
    showSecondaryAction: boolean;
    secondaryActionLabel: string;
    secondaryActionVariant: string;
    secondaryActionStatus: string;
    secondaryActionDisabled: boolean;
    hideViewDetails: boolean;
    hideDropdownDetails: boolean;
    hideDropdownPreferences: boolean;
    jcef: boolean;
    _showDropdown: boolean;
    _toggleIcon: string;
    _toggleLabel: string;
    _toggleDropdown(): void;
    _handlePrimaryAction(): void;
    _handleSecondaryAction(): void;
    private _handleDocumentClick;
    private _clickedOutside;
    private _updatePreferencesDropdownPosition;
    render(): import('lit-html').TemplateResult;
}
