import { LitElement } from 'lit';
export declare class ActionMenuItem extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentMouseDown;
    disconnectedCallback(): void;
    status: 'error' | 'primary';
    set state(state: 'error' | 'primary');
    get state(): 'error' | 'primary';
    label: string;
    leftIconFill: boolean;
    leftIcon: string | undefined;
    rightIconFill: boolean;
    rightIcon: string | undefined;
    actionLabel: string;
    actionIcon: string | undefined;
    actionStatus: string;
    set actionState(state: string);
    get actionState(): string;
    notifications: number;
    notificationsStatus: string;
    set notificationsState(state: string);
    get notificationsState(): string;
    selected: boolean;
    disabled: boolean;
    hasNestedMenu: boolean;
    nestedMenuPosition: string;
    first: boolean;
    last: boolean;
    tooltipPosition: string;
    hideTooltip: boolean;
    constructor();
    _handleItemClick(): void;
    _handleKeydown(event: KeyboardEvent): void;
    _handleAction(event: Event): void;
    private _clickOutside;
    private _onDocumentMouseDown;
    private _unselectItem;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
