import { LitElement } from 'lit';

export type CatalogOption = {
    value: string;
    icon?: string;
};
export declare class SearchBar extends LitElement {
    static get styles(): import('lit').CSSResult[];
    get _input(): HTMLInputElement;
    set multiple(value: boolean);
    set icon(icon: string);
    set inputSize(size: string);
    set helpText(text: string);
    set invalid(status: boolean);
    set threshold(value: number);
    set searchTerms(data: string[]);
    set catalog(data: CatalogOption[]);
    set emptyDropdownText(text: string);
    set recentSearchesText(text: string);
    set recentSearches(value: boolean);
    set isCatalogLoading(value: boolean);
    set dropdownStyle(style: string);
    _multiple: boolean;
    _icon: string;
    _placeholder: string;
    _inputSize: string;
    _invalid: boolean;
    _helpText: string;
    _isFocused: boolean;
    _showClearButton: boolean;
    _threshold: number;
    _searchTerms: string[];
    _catalog: CatalogOption[];
    _filteredCatalog: CatalogOption[];
    _showDropdown: boolean;
    _isCatalogLoading: boolean;
    _emptyDropdownText: string;
    _recentSearches: boolean;
    _recentSearchesText: string;
    _dropdownStyle: string;
    _searchboxStyle: string;
    _showAllChips: boolean;
    _getSearchStyle(): string;
    get _inputValidity(): boolean;
    _handleClick(): void;
    _handleInput(): void;
    _handleFocusIn(): void;
    _handleFocusOut(): void;
    _handleKeyDown(e?: KeyboardEvent): void;
    _focusInput(): void;
    _clearSearch(): void;
    _hideDropdown(): void;
    _getFilterCatalog(filter: string): CatalogOption[];
    _generateSearchChips(): import('lit-html').TemplateResult<1>[];
    _generateFilterCatalog(): import('lit-html').TemplateResult<1>[];
    _dispatchSearchChange(): void;
    _closeDropdown(): void;
    observerConfig: {
        attributes: boolean;
        childList: boolean;
        subtree: boolean;
    };
    callback: (mutationList: any) => void;
    observer: MutationObserver;
    disconnectedCallback(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
