import { LitElement } from 'lit';
export declare class Widget extends LitElement {
    static get styles(): import('lit').CSSResult[];
    variant: string;
    icon: string | undefined;
    iconStatus: string | undefined;
    title: string;
    titleText: string;
    results: string | undefined;
    resultsState: string;
    resultsLabel: string;
    info: undefined;
    infoBadgeState: string;
    infoBadgeIcon: string;
    infoBadgeOutlined: boolean;
    notifications: number | undefined;
    notificationsState: string;
    helpText: string | null;
    hasAction: boolean;
    hasNext: boolean;
    hasClose: boolean;
    actionLabel: string | undefined;
    actionIcon: string | undefined;
    actionVariant: string;
    actionFill: boolean;
    actionDisabled: boolean;
    tooltipFixed: boolean;
    tooltipPosition: string;
    hideTooltip: boolean;
    hasScroll: boolean;
    folded: boolean;
    private _eventOptions;
    checkTextTruncate(event: MouseEvent): void;
    handleAction(): void;
    handleNext(): void;
    handleClose(): void;
    protected firstUpdated(): void;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    render(): import('lit-html').TemplateResult;
}
