import { LitElement } from 'lit';

export type FormSelectOption = {
    label: string;
    value: string;
};
export declare class FormSelectOptions extends LitElement {
    static get styles(): import('lit').CSSResult[];
    disconnectedCallback(): void;
    isOpen: boolean;
    elements: Array<FormSelectOption> | null;
    value: Array<FormSelectOption> | Array<string> | null;
    _value: Array<FormSelectOption> | null;
    type: 'default' | 'green';
    filter: string | null;
    multiple: boolean;
    tick: boolean;
    deselectable: boolean;
    selectAll: boolean;
    isDisplayed: boolean;
    readonly: boolean;
    disabled: boolean;
    boxShadow: boolean;
    advancedFilter: boolean;
    searchThreshold: number;
    filterThreshold: number;
    boxStyle: string;
    selectedCounter: number;
    ariaLabel: string | null;
    labelSelectAll: string;
    labelDeselectAll: string;
    emptySelectorLabel: string;
    emptyFilterLabel: string;
    _elementId: string;
    _elementSelectAll: string[];
    _style: string | null;
    _isAllSelected: boolean;
    updated(changedProps: Map<string, any>): void;
    firstUpdated(): Promise<void>;
    _updateSelectedValues(): void;
    _areAllElementsSelected(): void;
    _valueIsSelected(value: string): boolean;
    _manuallySelect(e: Event, value: string): void;
    _manuallySelectAll(e: Event): void;
    _returnSelecteAllValues(selectAll: boolean): void;
    _returnSelectedValues(value: string): void;
    selectFirstMatch(): void;
    moveFocus(): void;
    _focusEvent(e: Event): void;
    _blurEvent(e: Event): void;
    render(): import('lit-html').TemplateResult;
}
