import { LitElement } from 'lit';
export declare class TablePagination extends LitElement {
    static get styles(): import('lit').CSSResult[];
    set length(length: number);
    get length(): number;
    set pageSize(pageSize: number);
    get pageSize(): number;
    set pageSizeOptions(pageSizeOptions: number[]);
    get pageSizeOptions(): number[];
    set pageSizeOptionsDisabled(value: boolean);
    get pageSizeOptionsDisabled(): boolean;
    set currentIndex(currentIndex: number);
    get currentIndex(): number;
    set rowsPerPageText(rowsPerPageText: string);
    get rowsPerPageText(): string;
    set resultsText(resultsText: string);
    get resultsText(): string;
    set hidePaginationResults(value: boolean);
    get hidePaginationResults(): boolean;
    _length: number;
    _pageSizeOptions: number[];
    _pageSize: number;
    _totalPages: number;
    _currentIndex: number;
    _startIndex: number;
    _endIndex: number;
    _rowsPerPageText: string;
    _resultsText: string;
    _pageSizeOptionsDisabled: boolean;
    _hidePaginationResults: boolean;
    _next(): void;
    _prev(): void;
    _handleChange(): void;
    private _emitCurrentPage;
    private _reload;
    private _reset;
    private _getDefaultPageSize;
    _printStartIndex(): string;
    firstUpdated(): Promise<void>;
    willUpdate(changedProperties: any): void;
    render(): import('lit-html').TemplateResult;
}
