import { LitElement } from 'lit';

export type DssTimepickerOption = {
    value: string;
    state: string;
};
export declare class FormTimepicker extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    disconnectedCallback(): void;
    _addDropdownListener(): void;
    _removeDropdownListener(): void;
    _handleClickOut(event: any): void;
    _handleFocusOut(event: FocusEvent): void;
    _checkClickOutside(event: Event): void;
    _checkFocusOut(event: FocusEvent): void;
    _input: HTMLInputElement;
    _label: HTMLLabelElement;
    label: string;
    hideLabel: boolean;
    name: string;
    id: string;
    type: string;
    placeholder: string;
    value: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    step?: number;
    min?: number;
    max?: number;
    minLength?: number;
    maxLength: number;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    size: string;
    icon: string;
    helpText?: string;
    showDropdown: boolean;
    dropdown: string;
    dropdownPlacement: string;
    dropdownFixed: boolean;
    customTimeListOptions: DssTimepickerOption[];
    errorTimeFormatText: string;
    errorTimeOptionText: string;
    minHour: number;
    maxHour: number;
    minutesRange: number;
    private _defaultId;
    _getEffectiveId(): string;
    _isFocused: boolean;
    _isTruncated: boolean;
    _timePattern: RegExp;
    _timeSeparator: string;
    _timeInputOldValue: string;
    _placeholder: string;
    _helpText: string;
    _oldHelpText: string;
    _manualHourSelector: string;
    _manualMinuteSelector: string;
    _timeListOptions: string[];
    _customTimeListOptions: DssTimepickerOption[];
    _timeManualHourOptions: string[];
    _timeManualMinutesOptions: string[];
    _inputValidity: boolean;
    _isFirstUpdated: boolean;
    _popperInstanceList: any;
    _popperInstanceManual: any;
    firstUpdated(): Promise<void>;
    updated(changedProps: Map<string, unknown>): void;
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    render(): import('lit-html').TemplateResult;
    _handleClick(): void;
    _handleKeyDown(e: KeyboardEvent): void;
    _handleInput(): void;
    _onInput(): void;
    _handleValidity(): void;
    _handleFocusin(): void;
    _handleFocusout(): void;
    _focusInput(): void;
    _checkInputOverflow(): void;
    _emitInput(): void;
    _emitChange(): void;
    _dispatchValueChange(): void;
    _createPopperList(): void;
    _createPopperManual(): void;
    _closeDropdown(): void;
    _timeMask(value: string, limit: number, separator: any): string;
    _timeUnmask(value: string): string;
    _timeValidate(value: string): void;
    _updateTimeOptions(): void;
    _generateTimeListOptions(): string[];
    _generateTimeListOptionsHTML(options: string[], customOptions?: DssTimepickerOption[]): import('lit-html').TemplateResult[];
    _generateTimeManualHoursOptions(): string[];
    _generateTimeManualMinutesOptions(): string[];
    _generateTimeManualOptionsHTML(inputName: string, options: string[]): import('lit-html').TemplateResult[];
    _checkDisableTimeManualSelector(): boolean;
    _timeManualSelectorCancel(): void;
    _timeManualSelectorAccept(): void;
    _timeListOptionsScrollTo(): void;
    _timeManualOptionsScrollTo(value?: string): void;
}
