import { LitElement } from 'lit';
import { OptionItem } from '../../utils/property-types';
export declare class Select extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    disconnectedCallback(): void;
    _input: HTMLInputElement;
    _hiddenInput: HTMLInputElement;
    _combobox: HTMLInputElement;
    label: string;
    hideLabel: boolean;
    name: string;
    id: string;
    placeholder: string;
    value: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    step?: number;
    min?: number;
    max?: number;
    minLength?: number;
    maxLength?: number;
    pattern?: string;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    size: string;
    icon: string;
    helpText?: string;
    maskRegex?: string;
    maskReplace?: string;
    allowedChars?: string;
    unit?: string;
    inputPrefix?: string;
    hasActions: boolean;
    elements: OptionItem[] | null;
    selectedValue: string[] | null;
    placeholderOnDropdown: string;
    placeholderIfEmpty: string;
    type: string;
    multiple: boolean;
    tick: boolean;
    autoSort: boolean;
    deselectable: boolean;
    boxStyle: string;
    dropdownStyle: string;
    labelSelectAll: string;
    labelDeselectAll: string;
    filterThreshold: number;
    searchThreshold: number;
    selectAll: boolean;
    showDropdown: boolean;
    openWithSearch: boolean;
    advancedFilter: boolean;
    tooltipFixed: boolean;
    forceViewport: boolean;
    private _defaultId;
    _getEffectiveId(): string;
    _isFocused: boolean;
    _isTruncated: boolean;
    _onHoldInterval: number | null;
    _isFiltering: boolean;
    _inputValidity: boolean;
    _selectElements: number;
    _multipleSelectedCounter: number;
    private _portalManager;
    _isInitialized: boolean;
    _syncFromValue: boolean;
    _placeholder: string;
    _previousValue: string | null;
    _elements: OptionItem[];
    _filteredElements: OptionItem[];
    _copyElements: OptionItem[];
    _multipleSelection: string[];
    private visibleObserver;
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    updated(changedProps: Map<string, unknown>): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
    _syncFormValue(): void;
    _onChange(): void;
    _handleValidity(): void;
    _emitInput(): void;
    _emitChange(): void;
    _addListenerClickOutside(): void;
    _removeListenerClickOutside(): void;
    _handleClickOutside(event: any): void;
    private _enableAnimations;
    private _disableAnimations;
    private _initializeElements;
    private _setupSearchMode;
    private _applyValue;
    private _applyOpenWithSearch;
    private _applyElements;
    private _applySelectedValue;
    private _getSelectedElements;
    private _getFilteredElements;
    _applyDefaultFilter(filter: string, selectedElements: any[]): any[];
    _applyAdvancedFilter(filter: string, selectedElements: any[]): any[];
    _isFirstInitSelectedElements: boolean;
    private _initSelectedElements;
    _isOverflowChecked: boolean;
    _handleInputMouseOver: () => void;
    _checkTruncatedIfMultipleSelection(): void;
    _showSelectedValues(values: string[]): void;
    private _reorderElements;
    private _updateInputValue;
    _checkInputOverflow(): void;
    _handleClick(): void;
    _handleInput(): void;
    _handleFocusIn(): void;
    _handleFocusOut(event: any): void;
    _handleBlurEsc(): void;
    _handleOptionsFocusOut(): void;
    _handleKeyDown(e: KeyboardEvent): void;
    _cleanInput(): void;
    _keyboardFilterMatch(): void;
    _showPlaceholder(): void;
    _hidePlaceholder(): void;
    _getPortalCombobox(): Element | null | undefined;
    _handleSelectorChange(e: CustomEvent): void;
    _handleBlurSelector(dropdown: any, event: any): void;
    _updateInternalValue(value: string[]): void;
    _dispatchValueChange(multiple?: boolean): void;
    _dispatchFilterChange(): void;
    _toggleDropdown(): void;
    _closeDropdown(): void;
}
