import { LitElement } from 'lit';
export declare class ActionMenu extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _parentMouseDownHandler;
    private _parentKeyDownHandler;
    private _slotChangeHandler;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    _addDropdownListener(): void;
    _removeDropdownListener(): void;
    _handleOutsideClick(event: any): void;
    _handleFocusOut(event: FocusEvent): void;
    _handleConnectedCallback(): void;
    private visibleObserver;
    fullWidth: boolean;
    position: string;
    disablePopper: boolean;
    disableParentClick: boolean;
    open: boolean;
    dropdownFixed: boolean;
    _cleanupFloating: (() => void) | null;
    _referenceEl: HTMLElement | null;
    _floatingEl: HTMLElement | null;
    _parent: HTMLElement | null;
    _trigger: HTMLElement | null;
    _isVisible: boolean;
    _disableClickOutside: boolean;
    _isFirstUpdate: boolean;
    _createFloatingInstance(parent: HTMLElement): void;
    _updateFloatingPosition(): Promise<void>;
    private _openByParent;
    private _handleCloseAllMenus;
    private _handleSlotChange;
    private _checkClickOutside;
    private _checkFocusOut;
    _closeMenu(): void;
    _initActionMenu(): void;
    firstUpdated(): Promise<void>;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    render(): import('lit-html').TemplateResult<1>;
}
