import { LitElement } from 'lit';
export declare class SidemenuListItem extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentClickBound;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    label: string;
    icon: string;
    selected: boolean;
    disabled: boolean;
    expanded: boolean;
    hasNestedMenu: boolean;
    notifications: number;
    notificationsStatus: string;
    set notificationsState(state: string);
    get text(): string;
    nestedMenuPosition: string;
    focusEnabled: boolean;
    private get _notificationBadge();
    _isHover: boolean;
    _isActive: boolean;
    _showItemDropdown: boolean;
    _isFocused: boolean;
    private _clickedOutsideItem;
    _handleDocumentClick(event: Event): void;
    _handleClick(): void;
    _handleMouseEnter(): void;
    _handleMouseLeave(): void;
    _handleMouseDown(): void;
    _handleMouseUp(): void;
    _handleKeyDown(event: KeyboardEvent): void;
    _handleFocusout(event: any): void;
    _toggleTooltip(): void;
    _closeItemDropdown(): void;
    focusItem(): void;
    blurItem(): void;
    private _tooltip;
    private _dropdown;
    _getDropdownFixedPosition(): void;
    _getTooltipFixedPosition(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
