import { LitElement } from 'lit';

export declare class Sidemenu extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentClickBound;
    private _handleResizeBound;
    private _handleContainerScrollBound;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    set expanded(value: boolean);
    set disabled(value: boolean);
    set toggleLabel(value: string);
    set createLabel(value: string);
    set createMenuPosition(value: string);
    set createNotifications(value: number);
    set createDisabled(value: boolean);
    set hideCreateMenu(value: boolean);
    set scrollContainerClass(value: string);
    _disabled: boolean;
    _expanded: boolean;
    _toggleDisabled: boolean;
    _toggleLabel: string;
    _hideCreateMenu: boolean;
    _createDisabled: boolean;
    _createLabel: string;
    _createMenuPosition: string;
    _createNotifications: number;
    _showCreateDropdown: boolean;
    _scrollContainerClass: string;
    private get _createNotification();
    private get _createSection();
    private _propagateProperties;
    private _handleResize;
    private _clickedOutsideCreateMenu;
    _closeCreateDropdown(): void;
    _handleDocumentClick(event: Event): void;
    _toggleCreateMenu(): void;
    _toggleSidemenu(): void;
    _handleCreateMouseEnter(): void;
    _handleCreateMouseLeave(): void;
    _handleCreateMouseDown(): void;
    _handleCreateFocusout(event: any): void;
    _handleCreateMouseUp(): void;
    private _dropdown;
    private get _scrollContainer();
    private _getCreateDropdownFixedPosition;
    _handleContainerScroll(): void;
    firstUpdated(): Promise<void>;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    render(): import('lit-html').TemplateResult<1>;
}
