import { LitElement } from 'lit';

export declare class InputField extends LitElement {
    static get styles(): import('lit').CSSResult;
    set value(value: string);
    set type(type: string);
    set label(label: string);
    set description(description: string);
    set placeHolder(placeHolder: string);
    set required(required: boolean);
    set disabled(disabled: boolean);
    set readonly(readonly: boolean);
    set icon(icon: string);
    set clearable(clearable: boolean);
    set showError(showError: boolean);
    set maxLength(maxLength: number);
    set minLength(minLength: number);
    set max(max: number);
    set min(min: number);
    set step(step: number);
    get _input(): HTMLInputElement | null | undefined;
    private _type;
    private _value;
    private _label;
    private _description;
    private _placeHolder;
    private _icon;
    private _maxLength;
    private _minLength;
    private _max;
    private _min;
    private _step;
    private _isInputFocused;
    private _isGroupFocusedVisible;
    private _isTypeNumeric;
    private _clearable;
    private _showError;
    private _required;
    private _disabled;
    private _readonly;
    private _handleInput;
    private _handleKeypress;
    private _handleKeyup;
    private _handleFocus;
    private _handleFocusOut;
    private _handleBlur;
    private _handelLabelClick;
    private _cleanInput;
    private _stepUp;
    private _stepDown;
    private _dispatchValueChange;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult<1>;
}
