import { LitElement } from 'lit';

export declare class HeaderMenuProfessional extends LitElement {
    static get styles(): import('lit').CSSResult[];
    private _handleDocumentClickBound;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    set size(value: string);
    set disabled(value: boolean);
    set name(value: string);
    set center(value: string);
    set collegiate(value: string);
    set infoLabel(value: string);
    set collegiateLabel(value: string);
    set preferencesLabel(value: string);
    set detailsLabel(value: string);
    set detailsHref(value: string);
    set detailsIcon(value: string);
    set detailsIconPosition(value: string);
    set logoutLabel(value: string);
    set logoutIcon(value: string);
    set logoutIconPosition(value: string);
    set hideDropdownDetails(value: boolean);
    set hideDropdownPreferences(value: boolean);
    _hideDropdownDetails: boolean;
    _hideDropdownPreferences: boolean;
    _size: string;
    _name: string | undefined;
    _center: string | undefined;
    _collegiate: string | undefined;
    _disabled: boolean;
    _showDropdown: boolean;
    _toggleIcon: string;
    _infoLabel: string;
    _collegiateLabel: string;
    _preferencesLabel: string;
    _detailsLabel: string;
    _detailsHref: string | undefined;
    _detailsIcon: string | undefined;
    _detailsIconPosition: string;
    _logoutLabel: string;
    _logoutIcon: string;
    _logoutIconPosition: string;
    _toggleDropdown(): void;
    _handleLogout(): void;
    private _handleDocumentClick;
    private _clickedOutside;
    render(): import('lit-html').TemplateResult<1>;
}
