import { LitElement } from 'lit';

export type DssTimepickerOption = {
    value: string;
    state: string;
};
export declare class Datepicker_ extends LitElement {
    static get styles(): import('lit').CSSResult[];
    get _input(): HTMLInputElement;
    get _labelSlot(): HTMLInputElement;
    get _label(): HTMLElement;
    set showTime(showTime: boolean);
    set showButtons(showButtons: boolean);
    set leftLabel(leftLabel: string);
    set rightLabel(rightLabel: string);
    set minDate(minDate: string);
    set maxDate(maxDate: string);
    set invalid(invalid: boolean);
    set inputSize(size: string);
    set helpText(text: string);
    set timepicker(value: string);
    set minutesRange(value: number);
    set minHour(value: number);
    set maxHour(value: number);
    set customTimeListOptions(options: DssTimepickerOption[]);
    set timepickerLabel(label: string);
    set value(value: string);
    set icon(icon: string);
    _timepickerLabel: string;
    _timepicker: string;
    _minutesRange: number;
    _minHour: number;
    _maxHour: number;
    _customTimeListOptions: DssTimepickerOption[];
    _icon: string;
    _placeholder: string;
    _externalPlaceholder: string;
    _previousDate: string;
    _minDate: string;
    _maxDate: string;
    _showCalendar: boolean;
    _showTime: boolean;
    _invalid: boolean;
    _showButtons: boolean;
    _required: boolean;
    _disabled: boolean;
    _readonly: boolean;
    _leftLabel: string;
    _rightLabel: string;
    _isFocused: boolean;
    _helpText: string;
    _inputSize: string;
    _inputValidity: boolean;
    observerConfig: {
        attributes: boolean;
        childList: boolean;
        subtree: boolean;
    };
    callback: (mutationList: any) => void;
    observer: MutationObserver;
    disconnectedCallback(): void;
    firstUpdated(): Promise<void>;
    _checkInputAttributes(): void;
    _handleValidity(): void;
    _closeDropdown(): void;
    _handleKeyUp(e: KeyboardEvent): void;
    _handleInput(event: any): void;
    _formatDate(value: string): string;
    _handleFocus(): void;
    _handleBlur(): void;
    _focusInput(): void;
    _handleClick(): void;
    _onDateChange(e: CustomEvent): void;
    _onCancel(): void;
    _dispatchValueChange(): void;
    render(): import('lit-html').TemplateResult;
}
