import { LitElement } from 'lit';

export declare class UploadBox extends LitElement {
    static get styles(): import('lit').CSSResult[];
    set size(value: 'xl' | 'md');
    set dragAndDropIcon(value: string);
    set dragAndDropMessage(value: string);
    set filesFormatMessage(value: string);
    set buttonLabel(value: string);
    set filesFormat(value: Array<string>);
    set fileFormatErrorMessage(value: string);
    set maxFileSize(value: number);
    private get _input();
    private _size;
    private _dragOver;
    private _files;
    private _disabled;
    private _dragAndDropIcon;
    private _dragAndDropMessage;
    private _filesFormatMessage;
    private _buttonLabel;
    private _filesFormat;
    private _fileFormatError;
    private _fileFormatErrorMessage;
    private _maxFileSize;
    private observerConfig;
    private callback;
    private observer;
    disconnectedCallback(): void;
    private _checkInputAttributes;
    private _onDragOver;
    private _onDragLeave;
    private _onDrop;
    private _onClick;
    private _onSlotInputChange;
    private _onFileInputChange;
    private _isValidFileFormat;
    private _isValidFileSize;
    private _handleFiles;
    private _removeFile;
    private _dispatchUploadFiles;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult<1>;
}
