import { LitElement } from 'lit';

export declare class UploadBox extends LitElement {
    static get styles(): import('lit').CSSResult[];
    set dragAndDropIcon(value: string);
    set dragAndDropMessage(value: string);
    set fileExplorerMessage(value: string);
    set filesFormatMessage(value: string);
    set buttonLabel(value: string);
    set filesFormat(value: Array<string>);
    set maxFileSize(value: number);
    private get _input();
    private _dragOver;
    private _files;
    private _disabled;
    private _dragAndDropIcon;
    private _fileExplorerMessage;
    private _dragAndDropMessage;
    private _filesFormatMessage;
    private _buttonLabel;
    private _filesFormat;
    private _fileFormatErrorMessage;
    private _fileSizeErrorMessage;
    private _fileFormatAndSizeErrorMessage;
    private _maxFileSize;
    private _fileErrors;
    private observerConfig;
    private callback;
    private observer;
    disconnectedCallback(): void;
    private _checkInputAttributes;
    private _onDragOver;
    private _onDragLeave;
    private _onDrop;
    private _onClick;
    private _onSlotInputChange;
    private _isValidFileFormat;
    private _isValidFileSize;
    private _validateFile;
    private _isAlreadyUploaded;
    private _handleInputFileChange;
    private _handleUploadedFiles;
    private _readFile;
    private _removeFile;
    private _reloadFile;
    private _dispatchUploadFiles;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult<1>;
}
