import { LitElement } from 'lit';
export type CatalogOption = {
    value: string;
    icon?: string;
    disabled?: boolean;
    key?: string;
    data?: any;
};
export declare class SearchBarCatalog extends LitElement {
    static get styles(): import('lit').CSSResult[];
    disconnectedCallback(): void;
    multiple: boolean;
    isOpen: boolean;
    isLoading: boolean;
    filter: string;
    threshold: number;
    advancedFilter: boolean;
    catalogTitle: string;
    catalog: CatalogOption[];
    recentSearchesTitle: string;
    recentSearches: CatalogOption[];
    resultsEmptyLabel: string;
    searchTerms: string[];
    catalogStyle: string | undefined;
    _floatingCombobox: HTMLElement;
    delay: number;
    private _parent?;
    private _initialParent;
    private _cleanupAutoUpdate?;
    private _showTimeout?;
    private _hideTimeout?;
    private _portalManager;
    private _isTabbingOut;
    _isFirstUpdated: boolean;
    _toggle: () => void;
    show(): void;
    private _executeShow;
    hide(): void;
    updateFloatingCombobox(): void;
    private _updatePosition;
    updated(changedProps: Map<string, unknown>): void;
    firstUpdated(): Promise<void>;
    _handleKeydown(event: KeyboardEvent): void;
    _handleFocusout(event: FocusEvent): void;
    moveFocus(): void;
    _focusSentinel(): void;
    _dispatchItemSelected(item: CatalogOption): void;
    _handleItemClick(e: Event, item: CatalogOption): void;
    _handleItemKeydown(event: KeyboardEvent, item: CatalogOption): void;
    render(): import('lit-html').TemplateResult;
}
