import { LitElement } from 'lit';
export declare class Textarea extends LitElement {
    static formAssociated: boolean;
    static get styles(): import('lit').CSSResult[];
    private internals;
    constructor();
    disconnectedCallback(): void;
    _textarea: HTMLTextAreaElement;
    label: string;
    hideLabel: boolean;
    name: string;
    id: string;
    placeholder: string;
    value: string;
    disabled: boolean;
    readonly: boolean;
    required: boolean;
    invalid: boolean;
    minLength?: number;
    maxLength?: number;
    inputmode?: string;
    autocapitalize: string;
    autocomplete: string;
    autocorrect: boolean;
    autofocus: boolean;
    spellcheck: boolean;
    rows: number;
    wrap: string;
    autoHeight: boolean;
    icon: string | undefined;
    size: string;
    helpText: string | null;
    _isTextareaFocused: boolean;
    _isGroupFocusedVisible: boolean;
    _lastValue: string | null;
    private _defaultId;
    _getEffectiveId(): string;
    updated(changedProps: Map<string, unknown>): void;
    formDisabledCallback(disabled: boolean): void;
    formResetCallback(): void;
    formStateRestoreCallback(state: string | null): void;
    firstUpdated(): Promise<void>;
    _updateHeight(): void;
    _handleInput(e: Event): void;
    _handleValidity(): void;
    _handleFocus(): void;
    _handleFocusOut(): void;
    _emitInput(): void;
    _emitChange(): void;
    render(): import('lit-html').TemplateResult;
}
