import { LitElement } from 'lit';

export type CatalogOption = {
    value: string;
    icon?: string;
};
export declare class SearchBar extends LitElement {
    static get styles(): import('lit').CSSResult[];
    _filter: string;
    get _input(): HTMLInputElement;
    innerFocus: boolean;
    set multiple(value: boolean);
    get multiple(): boolean;
    set icon(icon: string);
    get icon(): string;
    set inputSize(size: string);
    get inputSize(): string;
    set helpText(text: string);
    get helpText(): string;
    set invalid(status: boolean);
    get invalid(): boolean;
    set threshold(value: number);
    get threshold(): number;
    set searchTerms(data: string[]);
    get searchTerms(): string[];
    set catalog(data: CatalogOption[]);
    get catalog(): CatalogOption[];
    set emptyDropdownText(text: string);
    get emptyDropdownText(): string;
    set recentSearchesText(text: string);
    get recentSearchesText(): string;
    set recentSearches(value: boolean);
    get recentSearches(): boolean;
    set isCatalogLoading(value: boolean);
    get isCatalogLoading(): boolean;
    set dropdownStyle(style: string);
    get dropdownStyle(): string;
    advancedFilter: boolean;
    _multiple: boolean;
    _icon: string;
    _placeholder: string;
    _inputSize: string;
    _invalid: boolean;
    _helpText: string;
    _isFocused: boolean;
    _showClearButton: boolean;
    _threshold: number;
    _searchTerms: string[];
    _catalog: CatalogOption[];
    _filteredCatalog: CatalogOption[];
    _showDropdown: boolean;
    _isCatalogLoading: boolean;
    _emptyDropdownText: string;
    _recentSearches: boolean;
    _recentSearchesText: string;
    _dropdownStyle: string;
    _searchboxStyle: string;
    _showAllChips: boolean;
    _getSearchStyle(): string;
    get _inputValidity(): boolean;
    _handleClick(): void;
    _handleInput(): void;
    _handleFocusIn(): void;
    _handleFocusOut(): void;
    _handleKeyDown(e?: KeyboardEvent): void;
    _focusInput(): void;
    _clearSearch(): void;
    _hideDropdown(): void;
    _getFilterCatalog(filter: string): CatalogOption[];
    _applyDefaultFilter(filter: string): CatalogOption[];
    _applyAdvancedFilter(filter: string): CatalogOption[];
    _generateSearchChips(): import('lit-html').TemplateResult[];
    _generateFilterCatalog(): import('lit-html').TemplateResult[];
    _dispatchSearchChange(): void;
    _dispatchOnInput(): void;
    _closeDropdown(): void;
    observerConfig: {
        attributes: boolean;
        childList: boolean;
        subtree: boolean;
    };
    callback: (mutationList: any) => void;
    observer: MutationObserver;
    disconnectedCallback(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
