import { LitElement } from 'lit';
import { FontWeight } from '../../utils/property-types';
export declare class TableCell extends LitElement {
    static get styles(): import('lit').CSSResult[];
    connectedCallback(): void;
    size: 'auto' | 'sm' | 'md';
    fontWeight: FontWeight;
    align: 'left' | 'center' | 'right';
    colSpan: number;
    maxLines: number;
    variant: 'default' | 'header' | 'expanded';
    hover: boolean;
    highlight: boolean;
    sort: boolean;
    sortState: 'asc' | 'desc' | 'none';
    currentSortedColumn: string | undefined;
    borderRight: boolean;
    borderLeft: boolean;
    reverse: boolean;
    valueMaxWidth: boolean;
    slotMaxWidth: boolean;
    width: string | undefined;
    icon: string | undefined;
    iconTooltip: string | undefined;
    value: string | undefined;
    boldDivider: boolean;
    hideDivider: boolean;
    nested: boolean;
    hasIndicator: boolean;
    srOnly: boolean;
    updated(changedProps: Map<string, any>): void;
    isFirstUpdate: boolean;
    fontWeightBackup: FontWeight;
    isValueTruncaded: boolean;
    lastValue: string | undefined;
    _checkValueTruncated(event: MouseEvent): void;
    _getSortIcon(): string;
    _nextSortState(): void;
    _dispatchSort(): void;
    firstUpdated(): Promise<void>;
    render(): import('lit-html').TemplateResult;
}
